arrowParens: avoid
bracketSpacing: true
jsxBracketSameLine: false
printWidth: 80
proseWrap: preserve
rangeStart: 0
rangeEnd: Infinity
semi: true
singleQuote: false
tabWidth: 2
trailingComma: none
useTabs: false
